cvbuilder/urls.py
from django.urls import path
from . import views

app_name = 'cvbuilder'

urlpatterns = [
    path('', views.MainPage.as_view(), name='MainPage'),
    path('preview/', views.ResumePreview.as_view(), name='ResumePreview'),

    path('create_experience/', views.CreateExperience.as_view(), name='CreateExperience'),
    path('update_experience/<str:pk>', views.UpdateExperience.as_view(), name='UpdateExperience'),
    path('delete_experience/<str:pk>', views.DeleteExperience.as_view(), name='DeleteExperience'),
    path('save_experience_order/', views.SaveExperienceOrdering.as_view(), name='SaveExperienceOrdering'),

    path('create_skill/', views.CreateSkill.as_view(), name='CreateSkill'),
    path('delete_skill/<str:pk>', views.DeleteSkill.as_view(), name='DeleteSkill'),
    path('save_skill_order/', views.SaveSkillsOrder.as_view(), name='SaveSkillsOrder'),

    path('create_education/', views.CreateEducation.as_view(), name='CreateEducation'),
    path('update_education/<str:pk>/', views.UpdateEducation.as_view(), name='UpdateEducation'),
    path('delete_education/<str:pk>/', views.DeleteEducation.as_view(), name='DeleteEducation'),
    path('save_education_order/', views.SaveEducationOrder.as_view(), name='SaveEducationOrder'),

    path('create_language/', views.CreateLanguage.as_view(), name='CreateLanguage'),
    path('update_language/<str:pk>/', views.UpdateLanguage.as_view(), name='UpdateLanguage'),
    path('delete_language/<str:pk>/', views.DeleteLanguage.as_view(), name='DeleteLanguage'),
    path('save_language_order/', views.SaveLanguageOrder.as_view(), name='SaveLanguageOrder'),

    path('create_achievement/', views.CreateAchievement.as_view(), name='CreateAchievement'),
    path('update_achivement/<str:pk>/', views.UpdateAchievement.as_view(), name='UpdateAchievement'),
    path('delete_achievement/<str:pk>/', views.DeleteAchievement.as_view(), name='DeleteAchievement'),
    path('save_achievement_order/', views.SaveAchievementOrder.as_view(), name='SaveAchievementOrder'),

    path('create_publication/', views.CreatePublication.as_view(), name='CreatePublication'),
    path('update_publication/<str:pk>/', views.UpdatePublication.as_view(), name='UpdatePublication'),
    path('delete_publication/<str:pk>/', views.DeletePublication.as_view(), name='DeletePublication'),
    path('save_publication_order/', views.SavePublicationOrder.as_view(), name='SavePublicationOrder'),

    path('share/<str:code>', views.SharedResumePreview.as_view(), name='SharedResumePreview'),
    path('download_pdf/', views.PDFView.as_view(), name='pdf')
]

project-config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('cvbuilder.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cvbuilder/models.py
from django.db import models
from django.conf import settings
import random
import string


class Template(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Template'
        verbose_name_plural = 'Templates'


class Resume(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    image = models.ImageField(upload_to='cv_images', null=True, blank=True)
    name = models.CharField(max_length=255, blank=True, verbose_name='Name-Surname')
    description = models.CharField(max_length=255, blank=True)
    telephone = models.CharField(max_length=255, blank=True)
    email = models.EmailField(blank=True)
    career_summary = models.TextField(blank=True, verbose_name='Career Summary')
    linkedin = models.CharField(max_length=255, blank=True)
    github = models.CharField(max_length=255, blank=True)
    website = models.CharField(max_length=255, blank=True)
    template = models.ForeignKey(Template, on_delete=models.CASCADE, null=True, blank=True)
    code = models.CharField(max_length=8, default="", blank=True, unique=True)

    def __str__(self):
        return '%s - %s' % (self.name, self.description)

    def save(self, *args, **kwargs):
        if self.code == "": self.code = self.get_resume_code()
        super().save(*args, **kwargs)

    def get_resume_code(self):
        length = 8
        while True:
            code = ''.join(random.choices(string.ascii_uppercase, k=length))
            if Resume.objects.filter(code=code).count() == 0:
                break
        return code

    class Meta:
        verbose_name = 'Resume'
        verbose_name_plural = 'Resumes'


class Experience(models.Model):
    title = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    duration = models.CharField(max_length=255)
    text = models.TextField(blank=True)
    tech = models.TextField(blank=True)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='experiences')
    order = models.IntegerField(blank=False, default=100_000)

    def tech_as_list(self):
        tech_list = ""
        if not self.tech == "":
            tech_list = self.tech.replace(", ", ",").split(',')
            tech_list = [x[0].upper() + x[1:] for x in tech_list]
        return tech_list

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Experience'
        verbose_name_plural = 'Experiences'


class Skill(models.Model):
    title = models.CharField(max_length=38)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='skills')
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'


class Education(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255, verbose_name='Department')
    duration = models.CharField(max_length=255)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='educations')
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Education'
        verbose_name_plural = 'Educations'


class Achievement(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='achievements')
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Achievement'
        verbose_name_plural = 'Achievements'


class Language(models.Model):
    title = models.CharField(max_length=255)
    level = models.CharField(max_length=255)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='languages')
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Language'
        verbose_name_plural = 'Languages'


class Publication(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='publications')
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Publication'
        verbose_name_plural = 'Publications'

cvbuilder/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from .mixins import LoginRequiredMixin
from .models import (Education, Resume, Experience,
                     Skill, Language, Achievement, Publication)
from .forms import ResumeForm, ExperienceForm
from django.contrib import messages
from django.urls import reverse
from .mixins import (OwnerResumeUpdateView, OwnerResumeCreateView,
                     OwnerResumeDeleteView, SaveModelOrderMixin)
from wkhtmltopdf.views import PDFTemplateView


# ---- DOWNLOAD AS PDF ---- #

class PDFView(PDFTemplateView):
    cmd_options = {
        'margin-top': 0,
        'margin-left': 0,
        'margin-right': 0,
        'margin-bottom': 3,
    }

    def get_filename(self):
        resume = Resume.objects.get(user=self.request.user)
        return resume.name.replace(" ", "_") + '_Resume.pdf'

    def get_template_names(self):
        return self.get_template_name_color()['template_name']

    def get_context_data(self, **kwargs):
        context = super(PDFView, self).get_context_data(**kwargs)
        resume = Resume.objects.get(user=self.request.user)
        context = {
            'resume': resume,
            'experiences': resume.experiences.all().order_by('order'),
            'skills': resume.skills.all().order_by('order'),
            'educations': resume.educations.all().order_by('order'),
            'languages': resume.languages.all().order_by('order'),
            'achievements': resume.achievements.all().order_by('order'),
            'publications': resume.publications.all().order_by('order'),
            'color': self.get_template_name_color()['color'],
        }
        return context

    def get_template_name_color(self):
        template_name = 'cvbuilder/resumes/default.html'
        resume = Resume.objects.get(user=self.request.user)
        color = 'blue'
        template = resume.template
        if not template is None:
            if not template.name == "":
                template_name = 'cvbuilder/resumes/' + template.name.split(" ")[0].lower() + '.html'
                color = template.name.split(" ")[1].lower()
        return {
            'template_name': template_name,
            'color': color
        }


# ---- MAIN PAGE - EDIT OF DETAILS ---- #

class MainPage(LoginRequiredMixin, View):
    template_name = 'cvbuilder/0_mainpage.html'

    def get(self, request):
        try:
            resume = Resume.objects.get(user=request.user)
        except Resume.DoesNotExist:
            resume = Resume(user=request.user, name=request.user.username)
            resume.save()

        ctx = {
            'resume': resume,
            'form': ResumeForm(instance=resume),
            'experiences': resume.experiences.all().order_by('order'),
            'skills': resume.skills.all().order_by('order'),
            'educations': resume.educations.all().order_by('order'),
            'languages': resume.languages.all().order_by('order'),
            'achievements': resume.achievements.all().order_by('order'),
            'publications': resume.publications.all().order_by('order'),
        }
        return render(request, self.template_name, ctx)

    def post(self, request):
        resume = Resume.objects.get(user=request.user)
        form = ResumeForm(request.POST, request.FILES, instance=resume)
        if not form.is_valid: return render(request, self.template_name, {'form': form})
        form.save()
        messages.info(request, 'Resume information saved')
        return redirect(reverse('cvbuilder:MainPage'))


# --- RESUME VIEW AS HTML ---- #

class ResumePreview(LoginRequiredMixin, View):
    def get(self, request):
        resume = Resume.objects.get(user=request.user)
        template = resume.template

        # Default Template Values
        template_name = 'cvbuilder/resumes/default.html'
        color = 'blue'

        if not template is None:
            if not template.name == "":
                template_name = 'cvbuilder/resumes/' + template.name.split(" ")[0].lower() + '.html'
                color = template.name.split(" ")[1]

        if not resume.user == request.user: return redirect(reverse('pages:NoAccess'))
        ctx = {
            'resume': resume,
            'experiences': resume.experiences.all().order_by('order'),
            'skills': resume.skills.all().order_by('order'),
            'educations': resume.educations.all().order_by('order'),
            'languages': resume.languages.all().order_by('order'),
            'achievements': resume.achievements.all().order_by('order'),
            'publications': resume.publications.all().order_by('order'),
            'color': color.lower(),
        }
        return render(request, template_name, ctx)


# --- SHARED RESUME VIEW AS HTML ---- #

class SharedResumePreview(View):
    def get(self, request, code):
        resume = Resume.objects.get(code=code)
        template = resume.template

        # Default Template Values
        template_name = 'cvbuilder/resumes/default.html'
        color = 'blue'

        if not template is None:
            if not template.name == "":
                template_name = 'cvbuilder/resumes/' + template.name.split(" ")[0].lower() + '.html'
                color = template.name.split(" ")[1]

        ctx = {
            'resume': resume,
            'experiences': resume.experiences.all().order_by('order'),
            'skills': resume.skills.all().order_by('order'),
            'educations': resume.educations.all().order_by('order'),
            'languages': resume.languages.all().order_by('order'),
            'achievements': resume.achievements.all().order_by('order'),
            'publications': resume.publications.all().order_by('order'),
            'shared_view': 1,
            'color': color.lower(),
        }

        return render(request, template_name, ctx)


#### --------------------- CRUD VIEWS --------------------- ####

# ---- Experience CRUD --- #

class SaveExperienceOrdering(SaveModelOrderMixin):
    model = Experience


class CreateExperience(OwnerResumeCreateView):
    model = Experience
    form_class = ExperienceForm
    template_name = 'cvbuilder/crud_experience.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class UpdateExperience(OwnerResumeUpdateView):
    model = Experience
    form_class = ExperienceForm
    template_name = 'cvbuilder/crud_experience.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeleteExperience(OwnerResumeDeleteView):
    model = Experience
    success_url = reverse_lazy('cvbuilder:MainPage')


# ---- Skills CRUD --- #

class SaveSkillsOrder(SaveModelOrderMixin):
    model = Skill


class CreateSkill(OwnerResumeCreateView):
    model = Skill
    fields = ['title']
    template_name = 'cvbuilder/crud_skill.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeleteSkill(OwnerResumeDeleteView):
    model = Skill
    success_url = reverse_lazy('cvbuilder:MainPage')


# ---- Education CRUD --- #

class SaveEducationOrder(SaveModelOrderMixin):
    model = Education


class CreateEducation(OwnerResumeCreateView):
    model = Education
    fields = ['title', 'description', 'duration']
    template_name = 'cvbuilder/crud_education.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class UpdateEducation(OwnerResumeUpdateView):
    model = Education
    fields = ['title', 'description', 'duration']
    template_name = 'cvbuilder/crud_education.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeleteEducation(OwnerResumeDeleteView):
    model = Education
    success_url = reverse_lazy('cvbuilder:MainPage')


# ---- Language CRUD --- #

class SaveLanguageOrder(SaveModelOrderMixin):
    model = Language


class CreateLanguage(OwnerResumeCreateView):
    model = Language
    fields = ['title', 'level']
    template_name = 'cvbuilder/crud_language.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class UpdateLanguage(OwnerResumeUpdateView):
    model = Language
    fields = ['title', 'level']
    template_name = 'cvbuilder/crud_language.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeleteLanguage(OwnerResumeDeleteView):
    model = Language
    success_url = reverse_lazy('cvbuilder:MainPage')


# ---- Achievement CRUD --- #

class SaveAchievementOrder(SaveModelOrderMixin):
    model = Achievement


class CreateAchievement(OwnerResumeCreateView):
    model = Achievement
    fields = ['title', 'description']
    template_name = 'cvbuilder/crud_achievement.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class UpdateAchievement(OwnerResumeUpdateView):
    model = Achievement
    fields = ['title', 'description']
    template_name = 'cvbuilder/crud_achievement.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeleteAchievement(OwnerResumeDeleteView):
    model = Achievement
    success_url = reverse_lazy('cvbuilder:MainPage')


# ---- Publication CRUD --- #

class SavePublicationOrder(SaveModelOrderMixin):
    model = Publication


class CreatePublication(OwnerResumeCreateView):
    model = Publication
    fields = ['title', 'description']
    template_name = 'cvbuilder/crud_publication.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class UpdatePublication(OwnerResumeUpdateView):
    model = Publication
    fields = ['title', 'description']
    template_name = 'cvbuilder/crud_publication.html'
    success_url = reverse_lazy('cvbuilder:MainPage')


class DeletePublication(OwnerResumeDeleteView):
    model = Publication
    success_url = reverse_lazy('cvbuilder:MainPage')

cvbuilder/templates/cvbuilder/4_education.html
{% if educations %}

 <div class="card">
    <!-- Header -->
    <div class="card-header bg-dark text-center" id="heading4">
        <h3 class="mb-0">
            <button class="btn btn-link text-light" data-toggle="collapse" data-target="#collapse4" aria-expanded="true" aria-controls="collapse4">
                <span style="font-size:1.3em;">
                    <i class="fas fa-school mr-2"></i> Education
                </span>
            </button>
        </h3>
    </div>

    <div id="collapse4" class="collapse" aria-labelledby="heading4" data-parent="#accordion">

        <!-- Card Body -->
        <div class="card-body">
            
            <table class="table table-responsive-sm mb-0">
                
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col"></th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Duration</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>

                <form id="educationOrderingForm" method="post" action="{% url 'cvbuilder:SaveEducationOrder' %}"> {% csrf_token %}
                    
                    <tbody id="educations" class="text-center">

                        {% for education in educations %}

                            <tr data-lookup="{{ education.id }}">
                                <td><span class="handle_educations handle"></span></td>                
                                <td>{{ education.title }}</td>
                                <td>{{ education.description }}</td>
                                <td>{{ education.duration }}</td>
                                <td>
                                    <a href="{% url 'cvbuilder:UpdateEducation' education.id %}">
                                        <div class="text-center text-success">
                                            <i class="far fa-edit"></i>
                                        </div>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'cvbuilder:DeleteEducation' education.id %}">
                                        <div class="text-center text-danger">
                                            <i class="far fa-trash-alt"></i>
                                        </div>
                                    </a>
                                </td>
                            </tr>

                        {% endfor %}

                    </tbody>

                    <input type="hidden" id="educationOrderingInput" name="ordering">
                </form>

            </table>
        </div>
    </div>
</div>

{% endif %}

cvbuilder/templates/cvbuilder/5_language.html
{% if languages %}

 <div class="card">
    <!-- Header -->
    <div class="card-header bg-dark text-center" id="heading5">
        <h3 class="mb-0">
            <button class="btn btn-link text-light" data-toggle="collapse" data-target="#collapse5" aria-expanded="true" aria-controls="collapse5">
                <span style="font-size:1.3em;">
                    <i class="fas fa-globe-europe mr-1"></i> Languages
                </span>
            </button>
        </h3>
    </div>

    <div id="collapse5" class="collapse" aria-labelledby="heading5" data-parent="#accordion">
        <!-- Card Body -->
        <div class="card-body">
           

            <table class="table table-responsive-sm mb-0">
                
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col"></th>
                        <th scope="col">Language</th>
                        <th scope="col">Level</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>

                <form id="languageOrderingForm" method="post" action="{% url 'cvbuilder:SaveLanguageOrder' %}"> {% csrf_token %}
                    
                    <tbody class="text-center" id="languages">

                        {% for language in languages %}

                            <tr data-lookup="{{ language.id }}">
                                <td><span class="handle_languages handle"></span></td>                
                                <td>{{ language.title }}</td>
                                <td>{{ language.level }}</td>
                                <td>
                                    <a href="{% url 'cvbuilder:UpdateLanguage' language.id %}">
                                        <div class="text-center text-success">
                                            <i class="far fa-edit"></i>
                                        </div>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'cvbuilder:DeleteLanguage' language.id %}">
                                        <div class="text-center text-danger">
                                            <i class="far fa-trash-alt"></i>
                                        </div>
                                    </a>
                                </td>
                            </tr>

                        {% endfor %}

                    </tbody>

                    <input type="hidden" id="languageOrderingInput" name="ordering">
                </form>

            </table>


        </div>
    </div>
</div>

{% endif %}

cvbuilder/templates/cvbuilder/7_script.html
{% load static %}

<script src="{% static 'cvbuilder/Sortable.min.js' %}"></script>

<script>

    // Template
    $('#id_template').addClass('form-control');

    // Name 
    $('#id_name').addClass('form-control');
    $('#id_name').attr("placeholder", "Name - Surname");
    // Email
    $('#id_email').addClass('form-control');
    $('#id_email').attr("placeholder", "Email Address");
    // Phone Number
    $('#id_telephone').addClass('form-control');
    $('#id_telephone').attr("placeholder", "Phone Number");
    // Linkedin Address
    $('#id_linkedin').addClass('form-control');
    $('#id_linkedin').attr("placeholder", "LinkedIn Address");
    // Github
    $('#id_github').addClass('form-control');
    $('#id_github').attr("placeholder", "Github Address");
    // Personal Website
    $('#id_website').addClass('form-control');
    $('#id_website').attr("placeholder", "Personal Website");
    // Primary Title
    $('#id_description').addClass('form-control');
    $('#id_description').attr("placeholder", "Primary Title");
    // Career Summary
    $('#id_career_summary').addClass('form-control');
    $('#id_career_summary').attr("placeholder", "Career Summary");
    // Default option
    $("option:contains('---------')").text("Select Resume Template");

// ---- Sortable for Experiences - if exists

    if($('#experiences').length){
        const groups = document.getElementById('experiences');
        let sortable = Sortable.create(groups, {
            handle: '.handle_experiences',
            onEnd: () => {
                saveExperienceOrder();
            }
        });
    }

    function saveExperienceOrder() {
        const rows = $('#experiences > tr');
        let ids = [];
        for (let row of rows) {
            ids.push(row.dataset.lookup);
        }
        $('#orderingInput').val(ids.join(','));
        $('#orderingForm').submit();
    }

// ---- Sortable for Skills - if exists

    if($('#skills').length){
        const skills = document.getElementById('skills');
        let skills_sortable = Sortable.create(skills, {
            onEnd: () => {
                saveSkillsOrder();
            }
        });
    }

    function saveSkillsOrder(){
        var skill_rows = $('#skills > li')
        var skill_ids = [];
        for(var row of skill_rows){
            skill_ids.push(row.dataset.lookup);
        };
        $('#skillsOrderingInput').val(skill_ids.join(','));
        $('#skillsOrderingForm').submit();
    }

// ---- Sortable for Education - if exists

    if($('#educations').length){
        const educations = document.getElementById('educations');
        let educations_sortable = Sortable.create(educations, {
            onEnd: () => {
                saveEducationOrder();
            }
        });
    };

    function saveEducationOrder(){
        var education_rows = $('#educations > tr');
        var education_ids = [];
        for(var row of education_rows){
            education_ids.push(row.dataset.lookup);
        };
        $('#educationOrderingInput').val(education_ids.join(','));
        $('#educationOrderingForm').submit();
    }

// ---- Sortable for Language - if exists

    if($('#languages').length){
        const languages = document.getElementById('languages');
        let languages_sortable = Sortable.create(languages, {
            onEnd: () => {
                saveLanguageOrder();
            }
        });
    };

    function saveLanguageOrder(){
        var language_rows = $('#languages > tr');
        var language_ids = [];
        for(var row of language_rows){
            language_ids.push(row.dataset.lookup);
        };
        $('#languageOrderingInput').val(language_ids.join(','));
        $('#languageOrderingForm').submit();
    }

// ---- Sortable for Achievement - if exists

    if($('#achievements').length){
        const achievements = document.getElementById('achievements');
        let achievements_sortable = Sortable.create(achievements, {
            onEnd: () => {
                saveAchiementOrder();
            }
        });
    };

    function saveAchiementOrder(){
        var achievement_rows = $('#achievements > tr');
        var achievement_ids = [];
        for(var row of achievement_rows){
            achievement_ids.push(row.dataset.lookup);
        };
        $('#achievementOrderingInput').val(achievement_ids.join(','));
        $('#achievementOrderingForm').submit();
    }

// ---- Sortable for Publication - if exists

    if($('#publications').length){
        const publications = document.getElementById('publications');
        let publications_sortable = Sortable.create(publications, {
            onEnd: () => {
                savePublicationOrder();
            }
        });
    };

    function savePublicationOrder(){
        var publication_rows = $('#publications > tr');
        var publication_ids = [];
        for(var row of publication_rows){
            publication_ids.push(row.dataset.lookup);
        };
        $('#publicationOrderingInput').val(publication_ids.join(','));
        $('#publicationOrderingForm').submit();
    }

</script>

cvbuilder/templates/cvbuilder/8_cv_navbar.html
{% for message in messages %}
    <div class="alert alert-info mb-0 text-center" role="alert">
        {{ message }}
    </div>
{% endfor %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler mb-1" data-toggle="collapse" data-target="#navbarForCvBuilder">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-center" id="navbarForCvBuilder">
        <ul class="nav navbar-nav">
            <a class="btn btn-outline-light mr-1 mt-1 mb-1" href="{% url 'cvbuilder:MainPage' %}"><i class="fas fa-eye"></i> Resume Details</a>
            <a class="btn btn-outline-success mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreateExperience' %}"><i class="fas fa-plus"></i> Add Experience</a>
            <a class="btn btn-outline-success mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreateSkill' %}"><i class="fas fa-plus"></i> Add Skill</a>
            <a class="btn btn-outline-success mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreateEducation' %}"><i class="fas fa-plus"></i> Add Education</a>
            <a class="btn btn-outline-success mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreateLanguage' %}"><i class="fas fa-plus"></i> Add Language</a>
            <a class="btn btn-outline-success mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreateAchievement' %}"><i class="fas fa-plus"></i> Add Achievement</a>
            <a class="btn btn-outline-success mr-1 mt-1 mb-1" href="{% url 'cvbuilder:CreatePublication' %}"><i class="fas fa-plus"></i> Add Publication</a>
            <a class="btn btn-outline-warning mr-1 mt-1 mb-1" href="{% url 'cvbuilder:ResumePreview' %}"><i class="fas fa-search"></i> Preview Your Resume</a>
    </div>
</nav>

cvbuilder/templates/cvbuilder/crud_achievement.html
{% extends "cvbuilder/_base.html" %}
{% block title %} Ozan Tellioglu | Create/Edit {% endblock %}
{% block header %} Create/Edit Achievement {% endblock %}

{% block content %}

{% include 'cvbuilder/8_cv_navbar.html' %}

<div class="container-fluid text-center mt-3">    
  <div class="row content">
    <div class="col-sm-3"></div>

    <div class="col-sm-6 text-left"> 

        <form method="post">
                {% csrf_token %}

            <div class="mb-3">
                <label for="id_title" class="form-label"><b>Achievement</b></label>
                {{ form.title }}
            </div>

            <div class="mb-3">
                <label for="id_level" class="form-label"><b> Brief Description</b></label>
                {{ form.description }}
            </div>

            <input type="submit" class="btn btn-primary black-button-oz btn-block" value="Save">
        
        </form>

    </div>

    <div class="col-sm-3"></div>
  </div>
</div>

<div class="half-divider-oz"></div>

{% endblock %}

{% block script %}

    <script>
        $('#id_title').addClass('form-control');
        $('#id_title').attr('placeholder', 'Provide the achievement');
        $('#id_description').addClass('form-control');
        $('#id_description').attr('placeholder', 'Provide a brief description if applicable');
        $('#id_description').css('height', '40');
    </script>

{% endblock%}